// MichaelCraft service worker (Beta 1.1)
// Makes the game installable as an app and playable offline: everything the game
// loads is kept in a cache on your phone. When a new version is uploaded, change
// VERSION below so phones throw away the old copy.
const VERSION = 'michaelcraft-beta-1.1.5';
const PRECACHE = [
 "./",
 "index.html",
 "manifest.webmanifest",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-maskable-512.png",
 "icons/apple-touch-icon.png",
 "Sounds/sounds_bundle.js",
 "Textures/ores/rubyore_tile.png",
 "Textures/blocks/parasite_totem.png",
 "Textures/blocks/water_pump.png",
 "Textures/blocks/water_pipe.png",
 "Textures/blocks/sprinkler.png",
 "Textures/blocks/water_intake.png",
 "Textures/items/parasite_ingot.png",
 "Textures/items/parasite_chestplate.png",
 "Textures/items/tools/katana/parasite_katana.png",
 "Textures/items/tools/parasite/parasite_pickaxe.png",
 "Textures/items/tools/parasite/parasite_axe.png",
 "Textures/items/tools/parasite/parasite_shovel.png",
 "Textures/items/tools/parasite/parasite_sword.png",
 "Textures/ores/ironore_tile.png",
 "Textures/ores/cobaltore_tile.png",
 "Textures/ores/diamondore_tile.png",
 "Textures/ores/goldore_tile.png",
 "Textures/ores/coalore_tile.png",
 "Textures/items/cobalt_ingot.png",
 "Textures/items/arrow_ruby.png",
 "Textures/items/firefly_bottle.png",
 "Textures/items/charm_speed.png",
 "Textures/items/pumpkin_pie.png",
 "Textures/items/golden_apple.png",
 "Textures/items/iron_ingot.png",
 "Textures/items/charm_regen.png",
 "Textures/items/gold_ingot.png",
 "Textures/items/charm_damage.png",
 "Textures/items/cobalt_chestplate.png",
 "Textures/items/charm_dash.png",
 "Textures/items/door.png",
 "Textures/items/charm_feather.png",
 "Textures/items/ruby.png",
 "Textures/items/name_tag.png",
 "Textures/items/charm_frame.png",
 "Textures/items/ink_sac.png",
 "Textures/items/abyssal_armor.png",
 "Textures/items/arrow_diamond.png",
 "Textures/items/cooked_meat.png",
 "Textures/items/raw_iron.png",
 "Textures/items/arrow.png",
 "Textures/items/ruby_chunk.png",
 "Textures/items/glow_mushroom.png",
 "Textures/items/string.png",
 "Textures/items/paper.png",
 "Textures/items/raw_meat.png",
 "Textures/items/charm_jump.png",
 "Textures/items/map.png",
 "Textures/items/emerald.png",
 "Textures/items/leather.png",
 "Textures/items/apple.png",
 "Textures/items/boat.png",
 "Textures/items/bread.png",
 "Textures/items/leather_tunic.png",
 "Textures/items/shoji_wall.png",
 "Textures/items/glass_bottle.png",
 "Textures/items/iron_stick.png",
 "Textures/items/tonio_map.png",
 "Textures/items/diamond_chestplate.png",
 "Textures/items/iron_chestplate.png",
 "Textures/items/seeds.png",
 "Textures/items/samurai_armor.png",
 "Textures/items/wheat.png",
 "Textures/items/bone.png",
 "Textures/items/angel_wings.png",
 "Textures/items/diamond_chunk.png",
 "Textures/items/charm_health.png",
 "Textures/items/charm_power.png",
 "Textures/items/diamond.png",
 "Textures/items/bow.png",
 "Textures/items/coal.png",
 "Textures/items/ladder.png",
 "Textures/items/arrow_iron.png",
 "Textures/items/dojo_map.png",
 "Textures/items/raw_gold.png",
 "Textures/items/raw_cobalt.png",
 "Textures/items/abyss_map.png",
 "Textures/items/musket_ball.png",
 "Textures/items/stick.png",
 "Textures/items/ruby_chestplate.png",
 "Textures/items/tools/cobalt/cobalt_shovel.png",
 "Textures/items/tools/cobalt/cobalt_pickaxe.png",
 "Textures/items/tools/cobalt/cobalt_axe.png",
 "Textures/items/tools/cobalt/cobalt_sword.png",
 "Textures/items/tools/musket/tonios_musket.png",
 "Textures/items/tools/diamond/diamond_shovel.png",
 "Textures/items/tools/diamond/diamond_pickaxe.png",
 "Textures/items/tools/diamond/diamond_axe.png",
 "Textures/items/tools/diamond/diamond_sword.png",
 "Textures/items/tools/gold/gold_sword.png",
 "Textures/items/tools/gold/gold_axe.png",
 "Textures/items/tools/gold/gold_pickaxe.png",
 "Textures/items/tools/gold/gold_shovel.png",
 "Textures/items/tools/abyssal_war_hammer/abyssal_war_hammer.png",
 "Textures/items/tools/stone/stone_axe.png",
 "Textures/items/tools/stone/stone_shovel.png",
 "Textures/items/tools/stone/stone_pickaxe.png",
 "Textures/items/tools/stone/stone_sword.png",
 "Textures/items/tools/sledgehammer/sledgehammer.png",
 "Textures/items/tools/ruby/ruby_sword.png",
 "Textures/items/tools/ruby/ruby_pickaxe.png",
 "Textures/items/tools/ruby/ruby_shovel.png",
 "Textures/items/tools/ruby/ruby_axe.png",
 "Textures/items/tools/iron/iron_axe.png",
 "Textures/items/tools/iron/iron_shovel.png",
 "Textures/items/tools/iron/iron_pickaxe.png",
 "Textures/items/tools/iron/iron_sword.png",
 "Textures/items/tools/wood/wood_shovel.png",
 "Textures/items/tools/wood/wood_sword.png",
 "Textures/items/tools/wood/wood_pickaxe.png",
 "Textures/items/tools/wood/wood_axe.png",
 "Textures/items/tools/katana/senseis_katana.png",
 "Textures/items/tools/katana/katana.png",
 "Textures/blocks/exhaust_pipe.png",
 "Textures/blocks/chiseled_sandstone.png",
 "Textures/blocks/abyssal_alter.png",
 "Textures/blocks/door_bottom.png",
 "Textures/blocks/coal_block.png",
 "Textures/blocks/sandstone_slope_right.png",
 "Textures/blocks/obsidian.png",
 "Textures/blocks/diamond_block.png",
 "Textures/blocks/wood_plank.png",
 "Textures/blocks/door_top.png",
 "Textures/blocks/gas_furnace_on.png",
 "Textures/blocks/gold_block.png",
 "Textures/blocks/vent_base.png",
 "Textures/blocks/terracotta.png",
 "Textures/blocks/gem_cutter_on.png",
 "Textures/blocks/torch.png",
 "Textures/blocks/sandstone_slope_left.png",
 "Textures/blocks/cobblestone.png",
 "Textures/blocks/enchanting_table.png",
 "Textures/blocks/lantern.png",
 "Textures/blocks/cracked_stone_bricks.png",
 "Textures/blocks/furnace.png",
 "Textures/blocks/wood_platform.png",
 "Textures/blocks/ruby_block.png",
 "Textures/blocks/sandstone.png",
 "Textures/blocks/cobalt_block.png",
 "Textures/blocks/roof.png",
 "Textures/blocks/block_of_abyss.png",
 "Textures/blocks/roof_right.png",
 "Textures/blocks/charm_merger.png",
 "Textures/blocks/heart_of_the_abyss.png",
 "Textures/blocks/cactus.png",
 "Textures/blocks/iron_block.png",
 "Textures/blocks/door_closed_right_top_bottom.png",
 "Textures/blocks/vent.png",
 "Textures/blocks/abyssal_vine.png",
 "Textures/blocks/roof_left.png",
 "Textures/blocks/mossy_stone_bricks.png",
 "Textures/blocks/pumpkin.png",
 "Textures/blocks/gem_cutter_off.png",
 "Textures/blocks/gas_furnace.png",
 "Textures/blocks/door_closed_left_bottom___top.png",
 "Textures/blocks/chest.png",
 "Textures/blocks/door_open_top.png",
 "Textures/blocks/bed.png",
 "Textures/blocks/glass.png",
 "Textures/blocks/door_open_bottom.png",
 "Textures/blocks/stone_bricks.png",
 "Textures/blocks/crafting_table.png",
 "Textures/blocks/warped_block_of_abyss.png",
 "Textures/blocks/jack_o_lantern.png",
 "Textures/blocks/sea_lantern.png",
 "Textures/blocks/ladder.png",
 "Textures/blocks/emerald_block.png",
 "Textures/blocks/furnace_lit.png",
 "Textures/blocks/abyss_platform.png",
 "Textures/blocks/bookshelf.png",
 "Textures/blocks/doorway.png",
 "Textures/blocks/tonio/musket_rack.png",
 "Textures/blocks/tonio/tonio_sign.png",
 "Textures/blocks/tonio/musket_rack_empty.png",
 "Textures/blocks/japanese/japanese_post.png",
 "Textures/blocks/japanese/japanese_pilar.png",
 "Textures/blocks/japanese/torii_beam.png",
 "Textures/blocks/japanese/japanese_base_block_top.png",
 "Textures/blocks/japanese/katana_rack.png",
 "Textures/blocks/japanese/japanese_roof_eave.png",
 "Textures/blocks/japanese/japanese_roof.png",
 "Textures/blocks/japanese/sakura_leaves.png",
 "Textures/blocks/japanese/japanese_arch.png",
 "Textures/blocks/japanese/japanese_roof_ridge_end_left.png",
 "Textures/blocks/japanese/japanese_base_block_left_corner.png",
 "Textures/blocks/japanese/japanese_roof_tip_right.png",
 "Textures/blocks/japanese/japanese_roof_ridge_end_right.png",
 "Textures/blocks/japanese/tatami.png",
 "Textures/blocks/japanese/japanese_post_arch_conection_middle.png",
 "Textures/blocks/japanese/japanese_roof_tip_left.png",
 "Textures/blocks/japanese/japanese_post_arch_conection_right.png",
 "Textures/blocks/japanese/japanese_post_top.png",
 "Textures/blocks/japanese/shoji_wall.png",
 "Textures/blocks/japanese/stone_lantern.png",
 "Textures/blocks/japanese/japanese_post_arch_conection_left.png",
 "Textures/blocks/japanese/japanese_post_base.png",
 "Textures/blocks/japanese/japanese_roof_ridge.png",
 "Textures/blocks/japanese/paper_lantern.png",
 "Textures/blocks/japanese/japanese_roof_slope_right.png",
 "Textures/blocks/japanese/japanese_roof_slope_left.png",
 "Textures/blocks/japanese/japanese_base_block_right_corner.png",
 "Textures/nature/seaweed.png",
 "Textures/nature/wheat_stage1.png",
 "Textures/nature/tall_grass.png",
 "Textures/nature/gravel_tile.png",
 "Textures/nature/flower.png",
 "Textures/nature/stalagmite.png",
 "Textures/nature/dirt_tile.png",
 "Textures/nature/glow_mushroom.png",
 "Textures/nature/wheat_stage0.png",
 "Textures/nature/wheat_stage2.png",
 "Textures/nature/water_tile.png",
 "Textures/nature/farmland_tile.png",
 "Textures/nature/sand_tile.png",
 "Textures/nature/stone_tile.png",
 "Textures/nature/seaweed_top.png",
 "Textures/nature/grass_tile.png",
 "Textures/nature/wheat_stage3.png",
 "Textures/nature/bedrock_tile.png",
 "Textures/nature/leaf_tile.png",
 "Textures/nature/log_tile.png",
 "Textures/nature/cave_moss.png",
 "Textures/nature/stalactite.png",
 "Textures/nature/dead_bush.png",
 "Textures/entities/king_hand.png",
 "Textures/entities/king_of_the_abyss.png",
 "Textures/MISC/cave_inner_wall_tile.png",
 "Textures/HUD/hunger/half_hungerbar.png",
 "Textures/HUD/hunger/full_hungerbar.png",
 "Textures/HUD/hunger/no_hungerbar.png",
 "Textures/HUD/hearts/half_heart.png",
 "Textures/HUD/hearts/no_heart.png",
 "Textures/HUD/hearts/full_heart.png",
 "Sounds/music/desperation_BGM.mp3",
 "Sounds/music/final_stand.mp3",
 "Sounds/music/apex_parasite.mp3"
];

self.addEventListener('install', (e) => {
  // (each file on its own, so one missing file can't stop the install)
  e.waitUntil(caches.open(VERSION).then(c => Promise.all(PRECACHE.map(u => c.add(u).catch(() => { })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin, fonts = /fonts\.(googleapis|gstatic)\.com$/.test(url.hostname);
  if (!sameOrigin && !fonts) return;   // (multiplayer servers etc. go straight to the network)
  // the game page itself: newest version when online, the saved copy when offline
  if (req.mode === 'navigate' || url.pathname.endsWith('/index.html') || url.pathname.endsWith('/')) {
    e.respondWith(fetch(req).then(res => { const copy = res.clone(); caches.open(VERSION).then(c => c.put(req, copy)); return res; })
      .catch(() => caches.match(req, { ignoreSearch: true }).then(r => r || caches.match('index.html'))));
    return;
  }
  // music streams in pieces ("range" requests): play the whole saved file when we have it
  if (req.headers.has('range')) {
    e.respondWith(caches.match(url.href, { ignoreSearch: true }).then(r => r || fetch(req)));
    return;
  }
  // everything else: the saved copy if there is one, else download it and save it
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res && (res.ok || res.type === 'opaque')) { const copy = res.clone(); caches.open(VERSION).then(c => c.put(req, copy)); }
    return res;
  })));
});
